"""file_data nullable

Revision ID: 01faacf78025
Revises: b6ddcfafcb4a
Create Date: 2025-05-05 23:45:11.102852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01faacf78025'
down_revision: Union[str, None] = 'b6ddcfafcb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_data',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_data',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###
