"""aktualizacja bazy

Revision ID: 899b468ee9e0
Revises: 3edd8845c4a4
Create Date: 2025-05-12 22:37:21.638274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '899b468ee9e0'
down_revision: Union[str, None] = '3edd8845c4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_id', table_name='media')
    op.drop_table('media')
    op.alter_column('photos', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('photos', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.alter_column('photos', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('photos', 'description',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.create_table('media',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('media_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('file_data', sa.BLOB(), nullable=True),
    sa.Column('thumb_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('preview_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='media_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_media_id', 'media', ['id'], unique=False)
    # ### end Alembic commands ###
