"""add thumb_path to photos

Revision ID: 8b265810aca0
Revises: 6492a0149247
Create Date: 2025-05-05 23:28:20.993170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b265810aca0'
down_revision: Union[str, None] = '6492a0149247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'thumb_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('thumb_path', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
