"""file_data to LONGBLOB

Revision ID: c90d9296ab0c
Revises: 
Create Date: 2025-05-05 22:30:20.817439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c90d9296ab0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_data',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###
