"""add file_data & banned columns

Revision ID: fc80718c1fd1
Revises: 899b468ee9e0
Create Date: 2025-05-13 03:07:02.301370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc80718c1fd1'
down_revision: Union[str, None] = '899b468ee9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_cart_items_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('photo_categories')
    op.drop_index('ix_cart_id', table_name='cart')
    op.drop_table('cart')
    op.add_column('photos', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.alter_column('photos', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'photo_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('purchases', 'total_cost')
    op.drop_column('purchases', 'updated_at')
    op.drop_column('purchases', 'created_at')
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'banned')
    op.add_column('purchases', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('purchases', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('purchases', sa.Column('total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.alter_column('purchases', 'photo_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('photos', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('photos', 'file_data')
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_cart_id', 'cart', ['id'], unique=False)
    op.create_table('photo_categories',
    sa.Column('photo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='photo_categories_ibfk_2'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='photo_categories_ibfk_1'),
    sa.PrimaryKeyConstraint('photo_id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'categories', ['name'], unique=True)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('access_url', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_ibfk_1'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='order_items_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_date', mysql.DATETIME(), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_items_ibfk_1'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='cart_items_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_cart_items_id', 'cart_items', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    # ### end Alembic commands ###
